import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import React from 'react'
import CalOne from './calculator one'
import CalTwo from './calculator two'
import CalThree from './calculator three'


const inter = Inter({ subsets: ['latin'] })

export default class Home extends React.Component {
  constructor(props) {
    super(props)
    this.state = {
         component : <CalOne />
    }
    this.handleClick = this.handleClick.bind(this);
    this.handleClick2 = this.handleClick2.bind(this);
    this.handleClick3 = this.handleClick3.bind(this);
   };
   handleClick() {
     this.setState({ 
       component :  < CalOne />
    });
    document.getElementById("main").style.backgroundColor = "hsl(222, 26%, 31%)"
    document.getElementById("heading").style.color = "hsl(0, 0%, 100%)"
    document.getElementById("one").style.backgroundColor = "hsl(6, 63%, 50%)"
    
   }
    handleClick2() {
     this.setState({ 
       component : < CalTwo />
    })
     document.getElementById("main").style.backgroundColor = "hsl(0, 0%, 90%)";
     document.getElementById("heading").style.color = "black";
     document.getElementById("one").style.backgroundColor = "hsl(223, 31%, 20%)"

   }
    handleClick3() {
     this.setState({ 
       component : < CalThree />
    })
    document.getElementById("main").style.backgroundColor = "hsl(268, 75%, 9%)"
    document.getElementById("heading").style.color = "hsl(52, 100%, 62%)"
    document.getElementById("one").style.backgroundColor = "hsl(223, 31%, 20%)"
  }

  render() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
       <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link href="https://fonts.googleapis.com/css2?family=Barlow+Condensed&family=Bellefair&family=DM+Sans:wght@500&family=Inter:wght@200;600;700;900&family=League+Spartan:wght@900&family=Rubik&display=swap" rel="stylesheet"/>
      </Head>
        <main className={styles.main} id="main">
          <div className={styles.calculator}>
                <div className={styles.heading} id="heading">
                    <div>
                       <h3>calc</h3>
                    </div>
                    <div className={styles.theme} >
                       <h4>THEME</h4>
                       <div>
                         <p>1 2 3</p>
                         <div className={styles.toggle} id="toggle">
                            <input onClick={this.handleClick} class="button" type="radio" name="toggle" id= "one" className={styles.one} />
                            <input onClick={this.handleClick2}  class="button" type="radio" name="toggle" id={styles.two} className={styles.two} />
                            <input onClick={this.handleClick3}  class="button" type="radio" name="toggle" id={styles.three} className={styles.three} />
                          </div> 
                       </div>
                    </div>
                </div>
                {this.state.component}
          </div>
        </main>
    </>
  )
}}
